[package]
name = "conduit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"

diesel = { version = "1.4", features = ["postgres", "chrono", "uuidv07"] }
dotenv = "0.15"
chrono = "0.4"

uuid = { version = "0.8", features = ["serde", "v4"] }