services:
  app:
    container_name: app
    build: .
    command: 'bash -c "diesel setup && cargo watch --exec run"'
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/realworld-rust-actix-web
  db:
    container_name: db
    image: "postgres:14.0-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: realworld-rust-actix-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  .: