name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_integration_and_unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Create secrey.key
        run: cp secret.key.example secret.key
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  test_e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Create secrey.key
        run: cp secret.key.example secret.key
      - name: Create .env
        run: cp .env.example .env

      # TODO: ci skip temp
      # - name: Build
      #   run: cargo build --verbose
      # - name: Run server and ...
      #   run: cargo run --bin conduit &
      # - name: Run e2e test
      #   run: |
      #     cd e2e
      #     APIURL=http://localhost:8080/api sh ./run-api-tests.sh
